apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: owasp
    image: owasp/dependency-check
    args: 
    - "-s /data"
    - "-o /data"
    volumeMounts:
      - name: src
        mountPath: /data
  volumes:
  - name: src
    emptyDir: [:]
