apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: owasp
    image: owasp/dependency-check
    args: ["scan /src", "out /report"]
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - name: report
        mountPath: $WORKSPACE/report
      - name: src
        mountPath: $WORKSPACE/sdwar
  volumes:
    - name: report
      emptyDir: [:]
    - name: src
      emptyDir: [:]
      
