apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: owasp
    image: owasp/dependency-check
    args: 
    - "-s /root"
    - "-o /root"
    volumeMounts:
      - name: src
        mountPath: /root
  volumes:
  - name: src
    emptyDir: {} 
