apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: owasp
    image: owasp/dependency-check
    tty: true
    args: ["scan /src", "out /report"]
    volumeMounts:
      - name: report
        mountPath: $WORKSPACE/report
      - name: src
        mountPath: $WORKSPACE/sdwar
  - name: debian
    image: debian
    tty: true
  volumes:
    - name: report
      emptyDir: [:]
    - name: src
      emptyDir: [:]
      
