apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  containers:
  - name: owasp
    image: owasp/dependency-check
    command:
      - "dependency-check"
    args: 
    - "--scan /src"
    - "--out /report"
    volumeMounts:
      - name: src
        mountPath: /root/src
      - name: report
        mountPath: /root/report
      
